### ISSUE TITLE
denied: access forbidden for download container 

### ISSUE THREAD

**Issue by AndrzejOlender** [Tsuribori/pleroma-helm#6]
Unfortunately, I do not have permission to download the image
registry.gitlab.com/tsuribori/docker-pleroma
can this be opened to the world?

**Comment by Tsuribori** [comment]
It should be open now.

However it uses an outdated Pleroma version of 2.4.3 (current is 2.5.0) so I would recommend building your own image and using it instead: https://github.com/angristan/docker-pleroma

**Comment by AndrzejOlender** [comment]
Thanks for info
